version: '3.8'
services:
  db-ventas:
    image: mysql:8.0
    container_name: db-ventas
    environment:
      MYSQL_DATABASE: ventas_db
      MYSQL_ROOT_PASSWORD: root # Contraseña maestra
    volumes:
      - data-ventas:/var/lib/mysql
    networks:
      - devops-net
    deploy:
      resources:
        limits:
          memory: 250M

  backend-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: backend-ventas
    ports:
      - "8081:8080" # Redirige el 8081 externo al 8080 interno de Spring
    depends_on:
      - db-ventas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-ventas:3306/ventas_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx200m
    networks:
      - devops-net

  backend-despachos: # <--- Integrando el segundo microservicio
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: backend-despachos
    ports:
      - "8080:8080" # Redirige el 8080 externo al 8080 interno de Spring
    depends_on:
      - db-ventas # Usan la misma base de datos según tu estructura
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-ventas:3306/ventas_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx200m
    networks:
      - devops-net

  frontend:
    build: ./front_despacho
    container_name: frontend-app
    ports:
      - "80:80"
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge

volumes:
  data-ventas: