# Cambia localhost por el nombre del servicio en el docker-compose
spring.datasource.url=jdbc:mysql://db-ventas:3306/ventas_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate - Esto creará las tablas automáticamente (IE4)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
