
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate - Esto crear� las tablas autom�ticamente (IE4)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
