name: Deploy to AWS EC2

on:
  push:
    branches: [ "deploy" ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user # Ajustado para Amazon Linux
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/app"

      - name: Execute Manual Docker Build on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            
            # 1. Limpiar contenedores viejos
            docker-compose down || true
            
            # 2. Construir manualmente (Esto evita el error de buildx)
            docker build -t app-backend-ventas ./back-Ventas_SpringBoot/Springboot-API-REST
            docker build -t app-frontend ./front_despacho
            
            # 3. Levantar usando las imágenes locales recién creadas
            # Quitamos el flag --build para que no falle el compose
            docker-compose up -d